### ISSUE TITLE
Unexpected InvalidOperationException with optional parens on UNION...SELECT statement

### ISSUE THREAD

**Issue by calewis02** [bruce-dunwiddie/tsql-parser#69]
Hello,

Notice this statement:

`TSQLStatementReader.ParseStatements("SELECT 1 UNION (SELECT 2)");`

The result is:

```
InvalidOperationException: SELECT expected.
at TSQL.Clauses.Parsers.TSQLSelectClauseParser.Parse(ITSQLTokenizer tokenizer)
at TSQL.Statements.Parsers.TSQLLimitedSelectStatementParser.Parse()
at TSQL.Clauses.Parsers.TSQLSetOperatorClauseParser.Parse(ITSQLTokenizer tokenizer)   
at TSQL.Statements.Parsers.TSQLSelectStatementParser.Parse()   
at TSQL.Statements.Parsers.TSQLSelectStatementParser.TSQL.Statements.Parsers.ITSQLStatementParser.Parse()   at TSQL.TSQLStatementReader.MoveNext()   
at System.Collections.Generic.List1..ctor(IEnumerable1 collection)   
at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)   
at TSQL.TSQLStatementReader.ParseStatements(String tsqlText, Boolean useQuotedIdentifiers, Boolean includeWhitespace)
```

Removing the parens around the inner SELECT fixes the problem:

`TSQLStatementReader.ParseStatements("SELECT 1 UNION SELECT 2");`

However, according to [TSQL Syntax for the UNION operator](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/set-operators-union-transact-sql?view=sql-server-ver15#syntax), these optional parens should be permitted.

This seems like a bug...

**Comment by bruce-dunwiddie** [comment]
Thank you for letting me know. Optional parens are going to be the death of me.

I should be able to fix and release a new version in the next couple of days.

**Comment by bruce-dunwiddie** [comment]
A more problematic version of your use case appears to be

`(SELECT 1) UNION SELECT 2`

I had no idea this was a thing. This will require some more thought and research.

**Comment by bruce-dunwiddie** [comment]
I think it's now down to one more problematic case

```
WITH test AS
(
	SELECT 1 AS value
)
(
	SELECT *
	FROM
		test
)
```

**Comment by bruce-dunwiddie** [comment]
I think I have all of the situations covered now. https://www.nuget.org/packages/TSQL.Parser/1.5.2

**Comment by calewis02** [comment]
thanks!
